### ISSUE TITLE
Missing file CycloneTCP/ipv4/ipv4_routing.c

### ISSUE THREAD

**Issue by bullitmaster** [Oryx-Embedded/CycloneTCP#5]
Hi!
No file, similar to file _CycloneTCP/ipv6/ipv6_routing.c_ for ipv4!

Best Regards, bullitmaster!

**Comment by bullitmaster** [comment]
Contact support!

Best Regards, 
bullitmaster!

**Comment by google-mirror** [comment]
How to solve it?
